# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
---
include:
  - board: nrfmicro_13
    shield: algeboard_left
  - board: nrfmicro_13
    shield: algeboard_right
  - board: nrfmicro_13
    shield: settings_reset
